name: Facebook Stock Health Checker

on:
  schedule:
    - cron: '*/1 * * * *' # Every 15 minutes
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  check-stock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Stock Checker
        env:
          WORKER_KEY: ${{ secrets.WORKER_KEY }}
        run: python checker.py
